c_compiler_version:
  - 11

cxx_compiler_version:
  - 11

cuda_compiler:
  - cuda-nvcc

cuda11_compiler:
  - nvcc

cmake_version:
  - ">=3.26.4"

fmt_version:
  - ">=10.2.1,<11"

spdlog_version:
  - ">=1.13.0,<1.14"

sysroot_version:
  - "2.17"
